# Website details
name: "Konstantin Grudnitskiy"
description: "Python Developer"
email: "k.grudnitskiy@yandex.ru"
author: "gKonst"
lang: "ru"
locale: "RU"

# Jekyll
paginate: 10
markdown: kramdown
kramdown: 
    syntax_highlighter_opts:
        disable : true
gems: [jekyll-paginate]
timezone: Europe/Istanbul
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
url: "http://grudnks.github.io/"

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"
